parse_config:
  sticky_label: $$mdi:gesture-tap-hold$$

  raw_binding_map:
    "&none":
      tap: ""
      type: none

    "&hml LS(LA(LC(LCMD))) D":
      tap: D
      hold: "✦" # Hyper
    "&hmr LS(LA(LC(LCMD))) H":
      tap: H
      hold: "✦" # Hyper

    "&caps_word": $$mdi:alpha-w-box$$

    # Bluetooth
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:transfer-left$$
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:transfer-right$$

  zmk_keycode_map:
    # Symbols
    GRAVE: "`"
    TILDE: "~"
    EXCL: "!"
    AT: "@"
    HASH: "#"
    DLLR: $
    PRCNT: "%"
    CARET: ^
    AMPS: "&"
    STAR: "*"
    LPAR: (
    RPAR: )
    MINUS: "-"
    UNDER: _
    EQUAL: "="
    PLUS: "+"
    LBKT: "["
    LBRC: "{"
    RBKT: "]"
    RBRC: "}"
    BSLH: '\'
    PIPE: "|"
    SEMI: ";"
    COLON: ":"
    SQT: "'"
    DQT: '"'
    COMMA: ","
    DOT: "."
    FSLH: "/"

    # Navigation
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$
    HOME: $$mdi:transfer-left$$
    END: $$mdi:transfer-right$$

    # Whitespace
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    SPACE: $$mdi:keyboard-space$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$

    # Media
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$

    # Volume
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

draw_config:
  append_colon_to_layer_header: false
